;SQUARE WAVE LONGER THAN THE DELAY WHICH CAN BE GIVEN BY TIMERS ONLY MODE 1

ORG 0000H
	MOV TMOD, #10H
	MOV P1, #00H
AGAIN:  MOV R0, #5D 
	CPL P1.0
L1:	MOV TH1, #00H ;TIMER MAXXING OUT
	MOV TL1, #00H
	SETB TR1
HERE:   JNB TF1, HERE
	CLR TF1
	CLR TR1
	DJNZ R0, L1
	SJMP AGAIN
END
