ORG 0000H
    MOV R2,#0BH ;(0B = 11 SUBJECTS)
    MOV R0,#50H ;LOCATION OF CREDIT ARRAY
    MOV R1,#60H ;LOCATION OF GRADE ARRAY
    MOV DPTR,#3000H ;MAKING THE GRADE EQUIVALENT ARRAY (GRADE*CREDIT)
    MOV R3,#00H
    MOV R4,#00H
L1: MOV A,@R0
    MOV B,@R1
    MUL AB
    MOVX @DPTR,A
    ADD A,R4
    MOV R4,A ;SAVING SUMMATION OF (GRADE*CREDIT) IN R4
    MOV A,@R0
    ADD A,R3
    MOV R3,A ;SAVING SUMMATION OF (CREDIT) IN R4
    INC R0
    INC R1
    INC DPTR
    DJNZ R2,L1
    MOV A,R4
    MOV B,R3
    DIV AB ;DIVISION TO GET GPA
END
