ORG 0000H
    MOV R2,#0BH     ;(0B = 11 SUBJECTS)
    MOV R0,#50H     ;LOCATION OF CREDIT ARRAY
    MOV R1,#60H     ;LOCATION OF GRADE ARRAY
    MOV DPTR,#3000H ;MAKING THE GRADE EQUIVALENT ARRAY (GRADE*CREDIT)
    MOV R3,#00H     ;INITIALIZE REGISTER TO STORE SUM OF CREDITS
    MOV R4,#00H     ;INITIALIZE REGISTER TO STORE SUM OF GRADE*CREDITS
L1: MOV A,@R0       ;MOVE THE DATA BEING POINTED AT BY R0 (CREDIT ARRAY) TO THE A REGISTER
    MOV B,@R1       ;MOVE THE DATA BEING POINTED AT BY R1 (GRADE ARRAY) TO THE B REGISTER
    MUL AB          ;GRADE*CREDIT HAPPENS HERE
    MOVX @DPTR,A    ;MOVE THE PRODUCT TO EXTERNAL MEMORY
    ADD A,R4        ;ITERATIVE SUMMATION OF (GRADE*CREDIT)
    MOV R4,A        ;SAVING SUMMATION OF (GRADE*CREDIT) IN R4
    MOV A,@R0       ;MOVE THE DATA BEING POINTED AT BY R0 (CREDIT ARRAY) TO THE A REGISTER
    ADD A,R3        ;ITERATIVE SUMMATION OF (CREDIT)
    MOV R3,A        ;SAVING SUMMATION OF (CREDIT) IN R3
    INC R0          ;POINT TO NEXT CREDIT LOCATION
    INC R1          ;POINT TO NEXT GRADE LOCATION
    INC DPTR        ;POINT TO NEXT LOCATION WHERE GRADE*CREDIT WILL BE STORED IN THE NEXT ITERATION
    DJNZ R2,L1      ;LOOP TO LABEL (11 ITERATIONS). AFTER COMPLETION EXECUTE THE NEXT INSTRUCTION
    MOV A,R4        ;LOAD SUMMATION OF GRADE*CREDIT TO A
    MOV B,R3        ;LOAD SUMMATION OF CREDIT TO B
    DIV AB ;        ;DIVISION TO GET GPA
END
